# Generated by Django 4.2.9 on 2024-01-18 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_customer_created_at_alter_customer_modified_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('first_name', 'last_name', 'phone_number')},
        ),
    ]
